ruby_version: 'ruby-1.9.3-p545'
coverage:
  version: 2
  enabled: true
bundler_version: 1.10.6
test_pattern:
  - features/*.feature
  - spec/**_spec.rb
test_exclude_pattern:
  - spec/agent_spec.rb
tests:
  - echo 'ho'
cache:
  per_profile: true
  key_paths:
    - Gemfile
    - Gemfile.lock
    - solano.gemspec
    - lib/solano/version.rb

