ruby_version: 'ruby-1.9.3-p545'
hooks:
  pre_setup: echo 'pre_setup'
coverage:
  version: 2
  enabled: true
bundler_version: 1.10.6
test_pattern:
  - features/*.feature
  - spec/**_spec.rb
plan:
  - plan1
  - plan2
profiles:
  plan1:
    tests:
    - echo 'test plan 1'
    test_pattern:
      - features/*.feature
      - spec/**_spec.rb
    test_exclude_pattern:
          - spec/agent_spec.rb
  plan2:
    tests:
      - echo 'test plan 2'
    test_pattern:
      - features/*.feature
      - spec/**_spec.rb
    test_exclude_pattern:
      - spec/agent_spec.rb
cache:
  per_profile: true
  key_paths:
    - Gemfile
    - Gemfile.lock
    - solano.gemspec
    - lib/solano/version.rb

